# Named PUs with deliberately different names from clients
quarkus.hibernate-orm."inventory".client=cluster1
quarkus.hibernate-orm."inventory".packages=io.quarkiverse.mongohibernate.it.namedpus.inventory

quarkus.hibernate-orm."analytics".client=cluster2
quarkus.hibernate-orm."analytics".packages=io.quarkiverse.mongohibernate.it.namedpus.analytics

# Logging
quarkus.hibernate-orm."inventory".log.sql=true
quarkus.hibernate-orm."analytics".log.sql=true
