<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.quarkiverse.mongodb-hibernate</groupId>
        <artifactId>quarkus-mongodb-hibernate-parent</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>quarkus-mongodb-hibernate-integration-tests-parent</artifactId>
    <packaging>pom</packaging>
    <name>Quarkus MongoDB Hibernate - Integration Tests</name>

    <properties>
        <maven.deploy.skip>true</maven.deploy.skip>
        <gpg.skip>true</gpg.skip>
    </properties>

    <modules>
        <module>default-pu</module>
        <module>named-pus</module>
        <module>quarkus-data</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.quarkiverse.mongodb-hibernate</groupId>
                <artifactId>quarkus-mongodb-hibernate</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
